config/routes.rb
JqueryTextStatistics::Application.routes.draw do

  get 'try', to: 'try#index'
  get 'about', to: 'about#index'
  get 'contact', to: 'contact#index'

  root 'home#index'

  

end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

 helper :copyright

end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/try_controller.rb
class TryController < ApplicationController
  def index
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/copyright_helper.rb
module CopyrightHelper
  # CopyrightHelper Adds a method for a copyright time period
  # Author: Chris Allen Moore
  # example when parameter is before this year: copyright_years(2012) #=> "2012 - 2013"
  # example when parameter is this year: copyright_years(2013) #=> "2013"
  def copyright_years(year_started)
    raise ArgumentError, "Parameter must be an integer number" unless year_started.is_a?(Integer)
    raise ArgumentError, "year_started should not be in the future" if year_started > Time.new.year
    thisYear = Time.now.year

    if year_started == thisYear
      "#{year_started}"
    else
      "#{year_started} - #{thisYear}"
    end
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/try_helper.rb
module TryHelper
end

app/views/about/index.html.erb
<%= render 'home/topbar' %>
<div class="the-container">

  <div class="row">
    <div class="large-12 columns">
      <h1>About Text Statistics App</h1>

      <div>
        <h3>What technologies/strategies were used in building this project?</h3>
        <ul>
          <li>Ruby on Rails 4.0 Framework</li>
          <li>Ruby 2.0</li>
          <li>jQuery 2.0</li>
          <li>HTML5</li>
          <li>CSS3</li>
          <li>Foundation 4 front-end framework</li>
          <li>Sass</li>
          <li>LiveReload</li>
          <li>SEO Optimization</li>
          <li>Heroku hosted</li>
        </ul>
      </div>

    </div>
  </div>

</div>
<%= render 'home/footer' %>

app/views/contact/index.html.erb
<%= render 'home/topbar' %>
<div class="the-container">

  <div class="row">
    <div class="large-12 columns">
      <h1>Contact</h1>
    </div>
  </div>

</div>
<%= render 'home/footer' %>

app/views/home/_footer.html.erb
<footer>
  <div class="row">
    <div class="large-12 columns">
      <ul class="large-block-grid-3">
        <li>
          <%= link_to(image_tag('ClearTheNoise-logo-tsa-sm.png', alt: 'ClearTheNoise logo'), 'http://www.clearthenoise.com') %>
          <p class="mission">Sharing web development thoughts and bringing useful apps to market is what I do.</p>

          <p class="copyright">&copy; <%= copyright_years(2013) %> Chris Allen Moore. All Rights Reserved.</p>
        </li>
        <li></li>
        <li>
          <ul class="inline-list right">
            <li><%= link_to raw("<i class='icon-twitter-sign icon-2x'></i>"), 'https://twitter.com/chrisallenmoore', target: '_blank', rel: 'nofollow' %></li>
            <li><%= link_to raw("<i class='icon-google-plus-sign icon-2x'></i>"), 'https://plus.google.com/u/0/106209202247175897715/', target: '_blank', rel: 'nofollow' %></li>
            <li><%= link_to raw("<i class='icon-github icon-2x'></i>"), 'https://github.com/ClearTheNoise', target: '_blank', rel: 'nofollow' %></li>
            <li><%= link_to raw("<i class='icon-linkedin icon-2x'></i>"), 'http://www.linkedin.com/in/chrisallenmoore', target: '_blank', rel: 'nofollow' %></li>
          </ul>
        </li>
      </ul>

    </div>
  </div>
</footer>

app/views/home/_topbar.html.erb
<div class="contain-to-grid fixed">
  <nav class="top-bar" data-options="is_hover:false">
    <ul class="title-area">
      <!-- Title Area -->
      <li class="name">
        <h4><%= link_to(image_tag('TextStatisticsApp-logo-sm.png', alt: 'Text Statistics App logo'), root_path, class: 'brand') %></h4>
      </li>
      <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
      <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
    </ul>

    <section class="top-bar-section">
      <!-- Left Nav Section -->
      <ul class="right">
        <% if current_page?(controller: 'home') %>
            <li class='active'>
              <%= link_to('Home', root_path) %>
            </li>
        <% else %>
            <li>
              <%= link_to('Home', root_path) %>
            </li>
        <% end %>
        <% if current_page?(controller: 'try') %>
            <li class='active'>
              <%= link_to('Try it now!', try_path) %>
            </li>
        <% else %>
            <li>
              <%= link_to('Try it now!', try_path) %>
            </li>
        <% end %>
        <!--
        <% if current_page?(controller: 'about') %>
            <li class='active'>
              <%= link_to('About', about_path) %>
            </li>
        <% else %>
            <li>
              <%= link_to('About', about_path) %>
            </li>
        <% end %>
        <% if current_page?(controller: 'contact') %>
            <li class='active'>
              <%= link_to('Contact', contact_path) %>
            </li>
        <% else %>
            <li>
              <%= link_to('Contact', contact_path) %>
            </li>
        <% end %>-->
      </ul>

    </section>
  </nav>
</div>

app/views/home/index.html.erb
<% content_for :title, 'Text Statistics App by ClearTheNoise | Text Statistics for Writers' %>
<%= render 'topbar' %>

<div class="the-container">

  <div class="top-banner">
    <div class="row">
      <div class="large-12 columns">

        <h1>Text Statistics for writers</h1>

        <h4 class="subheader">Get useful text statistics for FREE, as in beer. Your readers will thank you.</h4>

        <%= link_to('Try It now!', try_path, class: 'medium button action-button') %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="large-12 columns">

      <section class="home-one">

          <div class="large-4 columns text-center">
            <span class="icon-stack icon-5x icon-primary">
              <i class="icon-sign-blank icon-stack-base"></i></i>
              <i class="icon-bullseye icon-light"></i>
            </span>
          </div>

          <div class="large-8 columns">
            <h2>How Text Statistics App can help</h2>

            <p>Writing is hard enough as it is. Whether you're writing articles, blog posts, or the next big
              novel, <%= link_to('Text Statistics App', try_path) %> helps you by giving useful stats to keep your
              writing honed in on your intended audience.</p>

            <p>With stuff like character counts, word counts and standardized readability levels, you'll be able to
              speak more fluently with your readers.</p>
          </div>

      </section>

      <hr>

      <section class="home-two">
        <ul class="large-block-grid-2">

          <li>
            <h2>Work how you like</h2>
            <h6>You can either: </h6>

            <p>Write in your favorite text editor, then simply copy and paste the text into
              <%= link_to('Text Statistics App', try_path) %>.</p>
            <h6>Or: </h6>

            <p>Use <%= link_to('Text Statistics App', try_path) %> to compose your writing.</p>
          </li>

          <li><h2>Minimalist approach</h2>

            <p><%= link_to('Text Statistics App', try_path) %> was created with the writer
              in mind. We've used a subtle color scheme; buttons, text statistic results, etc. minimize distraction
              which helps increase writing focus. </p>
            <%= link_to('Try It now!', try_path, class: 'medium button action-button') %>

          </li>

        </ul>
      </section>

    </div>
  </div>

</div>
<%= render 'footer' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]>
<html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>
<html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>
<html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!-->
<html lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8"/>

  <!-- Uncomment to make IE8 render like IE7 -->
  <!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  <!-- Set the viewport width to device width for mobile -->
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

  <title><%= content_for?(:title) ? yield(:title) : 'Untitled' %></title>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag '//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css' %>
  <%= javascript_include_tag 'vendor/custom.modernizr' %>
  <%= analytics_init if Rails.env.production? %>
  <%= csrf_meta_tags %>
</head>

<body>

<%= yield %>
</div>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</body>
</html>

app/views/try/_text_statistics.html.erb
<div class="row">
  <div class="large-12 columns">
    <form name="text-form" id="first-stop">
      <textarea name="msg" id="msg"></textarea>
    </form>
  </div>
</div>

<div class="row">
  <div class="small-12 small-centered columns">
    <ul class="inline-list">
      <li id="second-stop"><%= link_to('Load sample text', 'javascript:void(0)', class: 'small button sample-text action-button') %></li>
      <li id="fifth-stop"><%= link_to('Clear text & stats', 'javascript:void(0)', class: 'small button clear-text action-button') %></li>
    </ul>
  </div>
</div>

<section class="text-statistics">

  <div class="row">
    <div class="large-12 columns">
      <ul class="large-block-grid-3">
        <li>
          <div class="stats counts">
            <h2>Counts</h2>
            <ul>
              <li>Character Count Total: <span id="character-count"></span></li>
              <li>Word Count Total: <span id="word-count"></span></li>
              <li>Sentence Count Total: <span id="sentence-count"></span></li>
              <li>Syllable Count Total: <span id="syllable-count"></span></li>
            </ul>
          </div>
        </li>
        <li id="third-stop">
          <div class="stats averages">
            <h2>Averages</h2>
            <ul>
              <li>Avg Characters per Word: <span id="avg-characters-per-word"></span></li>
              <li>Avg Syllables per Word: <span id="avg-syllables-per-word"></span></li>
              <li>Avg Characters per Sentence: <span id="avg-characters-per-sentence"></span></li>
              <li>Avg Words per Sentence: <span id="avg-words-per-sentence"></span></li>
            </ul>
          </div>
        </li>
        <li>
          <div class="stats readability">
            <h2>Readability</h2>
            <ul>
              <li>Automated Readability Index: <span id="automated-readability-index"></span></li>
              <li>Coleman Liau Index: <span id="coleman-liau-index"></span></li>
              <li>Flesch Kindcaid Reading Ease: <span id="flesch-kincaid-reading-ease"></span></li>
              <li>Flesch Kindcaid Grade Level: <span id="flesch-kincaid-grade-level"></span></li>
            </ul>
          </div>
        </li>
      </ul>
    </div>
  </div>

  <div class="word-list">

    <div class="row">
      <div class="large-12 columns">
        <h3 id="fourth-stop">Individual word counts: </h3>
        <h6>List of the words in your text &amp; the number of times they appear in your text</h6>
        <br/>

        <!--- This is the list that stores the array items. --->
        <ol id="list">
          <!--- List items will be added dynamically. --->
        </ol>
      </div>
    </div>

  </div>

</section>

app/views/try/index.html.erb
<% content_for :title, 'Text Statistics App by ClearTheNoise | Try Text Statistics App for FREE now!' %>
<%= render 'home/topbar' %>
<div class="the-container">

  <div class="text-area">
    <%= render 'try/text_statistics' %>
  </div>

</div>
<%= render 'home/footer' %>

<ol class="joyride-list" data-joyride>
  <li data-id="first-stop" data-text="Next">
    <p>Take a tour.</p>

    <p>Your text goes here. Click or tap Next to see how to load some sample text.</p>

    <p>Already know what to do? Just close this box. :)</p>
  </li>
  <li data-id="second-stop" data-text="Next">
    <p>Go ahead, click or tap the "Load sample text" button to load the sample text.</p>

    <p>Scroll up to see the text was loaded.</p>
  </li>
  <li data-id="third-stop" data-text="Next">
    <p>To get the text statistics, just mouse over or tap on any one of the Counts, Averages or Readability sections and the text
      statistics will be automatically calculated for you.</p>
  </li>
  <li data-id="fourth-stop" data-text="Next">
    <p>This is where the words in your text get listed and counted for number of times they show in your text.</p>
  </li>
  <li data-id="fifth-stop" data-text="Next">
    <p>Click or tap this button anytime want to clear the text and the statistics.</p>

    <p>Have fun with and thanks for using Text Statistics App!</p>
  </li>
</ol>